apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5ndXNlcg==   # springuser en base64
  SPRING_DATASOURCE_PASSWORD: c3ByaW5ncGFzcw==   # springpass en base64
